service:
  name: service-flagd-ui
  namespace: aicares
image:
  repository: 952893849914.dkr.ecr.us-east-1.amazonaws.com/aicares-application/flagd-ui
  tag: latest
  pullPolicy: Always
containerPort: 4000
resources:
  limits:
    memory: "200Mi"
  requests:
    memory: "64Mi"
    cpu: "50m"
env:
  - name: SECRET_KEY_BASE
    value: "c7d014ca6b7fb171659ad9dba37a5c44c6262adaefe331aa3daa996988e93f42925d041d60ae34cd2867d4eee4c33dbf231c0c7a6911bfc6e438078f554b8622"
  - name: PHX_HOST
    value: "flagd-ui"
  - name: PORT
    value: "4000"
  - name: FLAGD_HOST
    value: "flagd"
  - name: FLAGD_PORT
    value: "8013"
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://otel-collector:4317"
  - name: OTEL_SERVICE_NAME
    value: "flagd-ui"
nodeSelector:
  eks.amazonaws.com/nodegroup: graviton-workers
